import { Router, type IRouter } from "express";
import healthRouter from "./health";
import initiativesRouter from "./initiatives";
import dashboardRouter from "./dashboard";
import documentsRouter from "./documents";
import settingsRouter from "./settings";
import validationsRouter from "./validations";
import backlogRouter from "./backlog";
import environmentRouter from "./environment";
import executionRouter from "./execution";
import governanceRouter from "./governance";
import portfolioRouter from "./portfolio";
import resourcesRouter from "./resources";
import reportsRouter from "./reports";
import jiraRouter from "./jira";
import jiraLinksRouter from "./jira-links";
import interviewAiRouter from "./interview-ai";
import interviewDraftsRouter from "./interview-drafts";
import initiativeBriefRouter from "./initiative-brief";
import { contentSafetyBoundary } from "../lib/content-safety";

const router: IRouter = Router();
router.use((req, res, next) => req.path === "/healthz" ? next() : contentSafetyBoundary(req, res, next));

router.use(healthRouter);
router.use(initiativesRouter);
router.use(dashboardRouter);
router.use(documentsRouter);
router.use(settingsRouter);
router.use(validationsRouter);
router.use(backlogRouter);
router.use(environmentRouter);
router.use(executionRouter);
router.use(governanceRouter);
router.use(portfolioRouter);
router.use(resourcesRouter);
router.use(reportsRouter);
router.use(jiraRouter);
router.use(jiraLinksRouter);
router.use(interviewAiRouter);
router.use(interviewDraftsRouter);
router.use(initiativeBriefRouter);

export default router;
